### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by looles** [MingfeiCheng/BehAVExplor#10]
Hello Dr CHENG, I am running experiments with high CPU usage, is this normal?
![image](https://github.com/user-attachments/assets/459e3e07-21f0-492b-bd65-7f695ef5dedd)

**Comment by MingfeiCheng** [comment]
Hi, it's normal. LGSVL and Apollo usually have high CPU usage.

**Comment by looles** [comment]
thanks!
