### ISSUE TITLE
如何实现apollo+lgsvl不用手动点开始进行测试ads

### ISSUE THREAD

**Issue by lsm2842035890** [MingfeiCheng/BehAVExplor#13]
你好程博士，不知道您lgsvl用的是否是yhuai博士的那个版本，我在使用的时候需要先点击api only，然后运行测试ads的脚本，最后点击lgsvl上的三角开始按钮才能开始运行，我想把人点击http//localhost的apionly和点击lgsvl的三角开始按钮的操作省略掉，具体该怎么实现~（比如第一个ads在场景1中跑完，然后它自动关掉，开启第二个场景2让ads在里面运行，全程不用人点击开始）
![`DXELPVR4H8FIM3@OM$V7K2](https://github.com/user-attachments/assets/f252f312-17dd-403a-8f45-98fdcf2f6abb)

![(2%M@ SABUCAC%N64RE41F9](https://github.com/user-attachments/assets/0cb14b00-6712-4594-83b6-aa8496841ca2)

**Comment by YuqiHuai** [comment]
@lsm2842035890 麻烦问下您后来实现了吗 我最近准备修复一下这个问题
