### ISSUE TITLE
Running prepare.sh from /apollo

### ISSUE THREAD

**Issue by YuqiHuai** [MingfeiCheng/BehAVExplor#6]
According to the setup process,

> Step 3: Compile required files in the apollo container (current path is /apollo)
> 
> sh BehAVExplor/prepare.sh
> bazel build //BehAVExplor:main

Instead of running `sh BehAVExplor/prepare.sh` when cwd is `/apollo`, should I actually run
```
/apollo$ cd BehAVExplor
/BehAVExplor$ sh prepare.sh
```

Because [the first line of prepare.sh](https://github.com/MingfeiCheng/BehAVExplor/blob/00c43e24d875512032b6c887a909c74a670171e3/prepare.sh#L1C1-L2C1) executes `pip install -r requirements.txt` and under `/apollo` there is no `requirements.txt`.

Currently, when I run `sh BehAVExplor/prepare.sh`, I get 
```
[yuqi@in-dev-docker:/apollo]$ sh BehAVExplor/prepare.sh 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Processing /apollo/BehAVExplor/PythonAPI-Apollo-async
```

**Comment by MingfeiCheng** [comment]
Hi Yuqi,

It seems the path is not correct. You can manually install the [requirements](https://github.com/MingfeiCheng/BehAVExplor/blob/main/requirements.txt). Thank you!
