### ISSUE TITLE
Freezed after around 2 hours

### ISSUE THREAD

**Issue by YuqiHuai** [MingfeiCheng/BehAVExplor#9]
Hi Mingfei,

After about 2 hours of running scenario 1, it got frozen. I attached the log from terminal below. Since SVL discontinued, I was using the SVL client you provided, and connected to a local cloud.

```
2024-03-16 05:13:48.237 | INFO     | common.simulator:load_map:64 - [Simulator] Loaded map: SanFrancisco_correct
2024-03-16 05:13:51.918 | INFO     | common.simulator:init_environment:246 - Load environment - Finish
2024-03-16 05:13:52.096 | INFO     | lgsvl.dreamview.dreamview:setup_apollo:314 - {'Camera': False, 'Canbus': False, 'Control': True, 'GPS': False, 'Guardian': False, 'Localization': True, 'Perception': False, 'Planning': True, 'Prediction': True, 'Radar': False, 'Recorder': False, 'Routing': True, 'Storytelling': True, 'Third Party Perception': False, 'Traffic Light': False, 'Transform': True, 'Velodyne': False}
2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Localization module...
2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Transform module...
2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Routing module...
2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Prediction module...
2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Planning module...
2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Control module...
2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Storytelling module...
2024-03-16 05:13:52.152 | INFO     | lgsvl.dreamview.dreamview:on_control_received:332 - Control message received
2024-03-16 05:13:54.193 | INFO     | common.simulator:run:316 - [Simulator] Set Apollo (EGO) destination: -435.52519353421843,410.3606234656769
nohup: appending output to 'nohup.out'
2024-03-16 05:13:57.365 | INFO     | lgsvl.simulator:run_custom:114 - [PythonAPI] simulator.run_custom
2024-03-16 05:13:57.365 | INFO     | lgsvl.remote:command_run:118 - [PythonAPI] Start Running
2024-03-16 05:14:28.533 | INFO     | common.simulator:run:457 - simulation finished, total frames: 301
2024-03-16 05:14:33.210 | INFO     | common.simulator:run:477 - [Simulator] Restart all simulator modules in case high delays.
```

Have you seen this issue before or is this likely a SVL issue due to not using official cloud?

**Comment by YuqiHuai** [comment]
I just terminated the process after submitting this issue and noticed the Traceback being
```
  File "/apollo/./bazel-bin/BehAVExplor/main.runfiles/apollo/BehAVExplor/main.py", line 150, in <module>
    fuzzer.loop(int(params['total_test_time'])) # seconds
  File "/apollo/./bazel-bin/BehAVExplor/main.runfiles/apollo/BehAVExplor/main.py", line 119, in loop
    scenario_recorder, scenario_id = runner.run(scenario_obj)
  File "/apollo/BehAVExplor/common/runner.py", line 52, in run
    sim_recorder = self.sim.run(scenario_obj, scenario_id, self.record_apollo_path)
  File "/apollo/BehAVExplor/common/simulator.py", line 478, in run
    utils.close_modules(dv, self.modules)
  File "/apollo/BehAVExplor/common/utils.py", line 13, in close_modules
    module_status = dv.get_module_status()
  File "/home/yuqi/.local/lib/python3.6/site-packages/lgsvl/dreamview/dreamview.py", line 221, in get_module_status
    self.ws.recv()
```
So it is actually Dreamview's websocket being broken and I have seen this before when we frequently communicate with Dreamview over socket. Is BehAVExplor expecting me to manually restart Dreamview when this problem happens?

**Comment by MingfeiCheng** [comment]
Hi Yuqi,

Sorry, I dont recall facing a similar situation before. So, I am not sure how to solve this issue effectively. Restart maybe a good solution. Thanks.

**Comment by YuqiHuai** [comment]
Hi Mingfei,

I ran BehAVExplor again and this time it seems to move on smoothly. However, after a few hours, I can no longer access Dreamview on localhost:8888, and BehAVExplor is still running.

See screenshot 
![Screenshot from 2024-03-18 10-06-24](https://github.com/MingfeiCheng/BehAVExplor/assets/34195403/45c0429e-0af9-42a8-9d57-60327e0ecdaf)


I've reported this to Apollo before but I cannot provide enough information for them to debug the issue.
https://github.com/ApolloAuto/apollo/issues/13134#issuecomment-1195865636

Dreamview's log suggests its backend is still working
```
I0318 10:03:33.893414 4047347 simulation_world_updater.cc:656] Constructed RoutingRequest to be sent:
waypoint {
  id: "lane_477"
  s: 18.651878762971553
  pose {
    x: 593241.49687995552
    y: 4135030.957659022
  }
}
waypoint {
  id: "lane_570"
  s: 59.999857800182347
  pose {
    x: 593130.360748291
    y: 4134914.525177
  }
}
W0318 10:03:36.611380 4047413 rate.cc:96] Detect forward jumps in time
I0318 10:03:38.099026 4047342 simulation_world_service.h:240] Has not received any data from /apollo/audio_detection
W0318 10:03:40.798460 4047413 rate.cc:96] Detect forward jumps in time
```

So likely this is an issue of Apollo's Dreamview and I'll close this issue.

**Comment by looles** [comment]
@YuqiHuai Hi, I'm having a similar problem, I get the following error when I first run it, can you help me out?![image](https://github.com/user-attachments/assets/7752e57a-3454-4345-95c4-3af25b43ad4e)

**Comment by YuqiHuai** [comment]
When you first run it? Did you compile an Apollo first? This looks like you have not compiled it, or you compiled it under root but not regular user (inside docker).

**Comment by looles** [comment]
1. I am running it for the first time; 2. Apollo is already compiled; 3. I retried it again with a normal user and it doesn't work;
![image](https://github.com/user-attachments/assets/09bfd239-c718-48f6-8160-468d7306b4f0)
![image](https://github.com/user-attachments/assets/a4560e8f-8399-49b9-8657-6a5a640f4bf0)
![image](https://github.com/user-attachments/assets/792ce039-f582-4d27-bd97-9c4ca45dbc0c)
![image](https://github.com/user-attachments/assets/5beb1402-255c-4211-8429-45a8b64c3723)
Can you determine where I am having problems with the steps based on the picture above?

**Comment by YuqiHuai** [comment]
Nope, cannot determine the issue yet. When you enter the container, can you run ‘cyber_recorder’?

**Comment by looles** [comment]
Hi, I have installed "cyber_recorder" as per the tutorial, but it still doesn't work.

**Comment by looles** [comment]
Hi, I have installed "cyber_recorder" as per the tutorial, but it still doesn't work.
![Uploading image.png…]()

![Uploading image.png…]()

**Comment by looles** [comment]
Hi, I have installed "cyber_recorder" as per the tutorial, but it still doesn't work.

**Comment by lsm2842035890** [comment]
> Hi Mingfei,
> 
> After about 2 hours of running scenario 1, it got frozen. I attached the log from terminal below. Since SVL discontinued, I was using the SVL client you provided, and connected to a local cloud.
> 
> ```
> 2024-03-16 05:13:48.237 | INFO     | common.simulator:load_map:64 - [Simulator] Loaded map: SanFrancisco_correct
> 2024-03-16 05:13:51.918 | INFO     | common.simulator:init_environment:246 - Load environment - Finish
> 2024-03-16 05:13:52.096 | INFO     | lgsvl.dreamview.dreamview:setup_apollo:314 - {'Camera': False, 'Canbus': False, 'Control': True, 'GPS': False, 'Guardian': False, 'Localization': True, 'Perception': False, 'Planning': True, 'Prediction': True, 'Radar': False, 'Recorder': False, 'Routing': True, 'Storytelling': True, 'Third Party Perception': False, 'Traffic Light': False, 'Transform': True, 'Velodyne': False}
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Localization module...
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Transform module...
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Routing module...
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Prediction module...
> 2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Planning module...
> 2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Control module...
> 2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Storytelling module...
> 2024-03-16 05:13:52.152 | INFO     | lgsvl.dreamview.dreamview:on_control_received:332 - Control message received
> 2024-03-16 05:13:54.193 | INFO     | common.simulator:run:316 - [Simulator] Set Apollo (EGO) destination: -435.52519353421843,410.3606234656769
> nohup: appending output to 'nohup.out'
> 2024-03-16 05:13:57.365 | INFO     | lgsvl.simulator:run_custom:114 - [PythonAPI] simulator.run_custom
> 2024-03-16 05:13:57.365 | INFO     | lgsvl.remote:command_run:118 - [PythonAPI] Start Running
> 2024-03-16 05:14:28.533 | INFO     | common.simulator:run:457 - simulation finished, total frames: 301
> 2024-03-16 05:14:33.210 | INFO     | common.simulator:run:477 - [Simulator] Restart all simulator modules in case high delays.
> ```
> 
> Have you seen this issue before or is this likely a SVL issue due to not using official cloud?

hello，Dr YuqiHuai,作者的svl跟您的svl版本同样需要修改config.yml里面cloud-url=http://localhost并且docker compose up --build -d吗，不清楚怎么使用他提供的svl，我还试了直接简单的双击exe，但是显示offline~

**Comment by lsm2842035890** [comment]
> Hi Mingfei,
> 
> After about 2 hours of running scenario 1, it got frozen. I attached the log from terminal below. Since SVL discontinued, I was using the SVL client you provided, and connected to a local cloud.
> 
> ```
> 2024-03-16 05:13:48.237 | INFO     | common.simulator:load_map:64 - [Simulator] Loaded map: SanFrancisco_correct
> 2024-03-16 05:13:51.918 | INFO     | common.simulator:init_environment:246 - Load environment - Finish
> 2024-03-16 05:13:52.096 | INFO     | lgsvl.dreamview.dreamview:setup_apollo:314 - {'Camera': False, 'Canbus': False, 'Control': True, 'GPS': False, 'Guardian': False, 'Localization': True, 'Perception': False, 'Planning': True, 'Prediction': True, 'Radar': False, 'Recorder': False, 'Routing': True, 'Storytelling': True, 'Third Party Perception': False, 'Traffic Light': False, 'Transform': True, 'Velodyne': False}
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Localization module...
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Transform module...
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Routing module...
> 2024-03-16 05:13:52.099 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Prediction module...
> 2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Planning module...
> 2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Control module...
> 2024-03-16 05:13:52.100 | INFO     | lgsvl.dreamview.dreamview:enable_apollo:283 - Starting Storytelling module...
> 2024-03-16 05:13:52.152 | INFO     | lgsvl.dreamview.dreamview:on_control_received:332 - Control message received
> 2024-03-16 05:13:54.193 | INFO     | common.simulator:run:316 - [Simulator] Set Apollo (EGO) destination: -435.52519353421843,410.3606234656769
> nohup: appending output to 'nohup.out'
> 2024-03-16 05:13:57.365 | INFO     | lgsvl.simulator:run_custom:114 - [PythonAPI] simulator.run_custom
> 2024-03-16 05:13:57.365 | INFO     | lgsvl.remote:command_run:118 - [PythonAPI] Start Running
> 2024-03-16 05:14:28.533 | INFO     | common.simulator:run:457 - simulation finished, total frames: 301
> 2024-03-16 05:14:33.210 | INFO     | common.simulator:run:477 - [Simulator] Restart all simulator modules in case high delays.
> ```
> 
> Have you seen this issue before or is this likely a SVL issue due to not using official cloud?

hi,Dr YuqiHuai,我尝试了把cloud_url改成了http://localhost,接着运行SORA-SVL中docker compose up--build -d 运行本地云，然后打开Dr Cheng修改过的simulator，似乎只修改config.yal.template没有起作用，这是怎么回事~

**Comment by YuqiHuai** [comment]
@lsm2842035890 最近快假期了可能回复不太及时

Mingfei提供的SVL就是官方的原版SVL，这个版本因为没有后端已经不能单独使用了。
SORA-SVL中要求改的是config.yml，您看看是不是改成模版文件了。

**Comment by lsm2842035890** [comment]
> @lsm2842035890 最近快假期了可能回复不太及时
> 
> Mingfei提供的SVL就是官方的原版SVL，这个版本因为没有后端已经不能单独使用了。 SORA-SVL中要求改的是config.yml，您看看是不是改成模版文件了。

对的，是template文件，里面cloud_url= https://wise.svlsimulator.com,我是需要把这个模板文件删掉然后重新新建一个config.yml把cloud_url 变成 http://localhost 嘛~
![SL}~J9{`UYZ12@$8V S`~L7](https://github.com/user-attachments/assets/851f7c0d-3d2e-4226-8853-4eaff93a2983)
![BI4{_Y5O7V@C(R~C((1M39K](https://github.com/user-attachments/assets/007441fb-db9d-4728-af3c-1a09fb3b82c8)

**Comment by YuqiHuai** [comment]
把.template去掉 config.yml里的cloud url要指向localhost @lsm2842035890

**Comment by lsm2842035890** [comment]
> 把.template去掉 config.yml里的cloud url要指向localhost @lsm2842035890

按照您说的这样，然后我打开之后，simulator面板上仍然会尝试连接 https://wise.svlsimulator.com
感觉应该还有一些地方也需要该成指向localhost
![W X0ZAQJ PXEJHJ5${JEXA5](https://github.com/user-attachments/assets/8f6fd1f1-29f1-419a-a628-8ee33c2a3d2f)

**Comment by YuqiHuai** [comment]
@lsm2842035890 很奇怪 看看 https://ics.uci.edu/~yhuai/SORA-SVL/simulation_ui/configuration.html 实在不行还可以从terminal启动svl，传入—cloudurl参数。
